<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Faker\Core\Uuid;

class Genero extends Model
{
    use HasFactory;

    protected  $fillable  = ['nome','is_active'];


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($obj){
            $obj->id = \Ramsey\Uuid\Uuid::uuid4();
        });
    }
}
